### ISSUE TITLE
Compatability with Vero V

### ISSUE THREAD

**Issue by dbischof90** [hissingshark/retrOSMCmk2#28]
Hi, 

How is the status regarding Vero V support? The installer does still restrict this addon to Vero 4(+) and I'm not sure I would want to mess around with the stuff here just to try out. :)

**Comment by hissingshark** [comment]
I hadn't realised I'd not pushed my test commits in time for the soft launch, until a user pointed it out on the forum (better than posting here as I don't monitor GitHub the same).  Then I started finishing some other changes...
It should have been working the day you posted, but you may have got in before the push!

Also my "beta setup" may differ from end users because of the dev packages I install, so useful to know if anything doesn't work.  I'm going to be doing a re-install from the published image soon to try and replicate that.

**Comment by dbischof90** [comment]
Hi! Well, not so fast :)

I just tried to do a clean install and get the following error:

```
= = = = = = = = = = = = = = = = = = = = =
Installing (binary) 'sdl2' : SDL (Simple DirectMedia Layer) v2.x
= = = = = = = = = = = = = = = = = = = = =

Downloading https://files.retropie.org.uk/binaries/bullseye/vero5/libsdl2-dev_2.0.20+1mali_armhf.deb.asc to /tmp/tmp.qWfjrH8kWC/libsdl2-dev_2.0.20+1mali_armhf.deb.asc ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
URL https://files.retropie.org.uk/binaries/bullseye/vero5/libsdl2-dev_2.0.20+1mali_armhf.deb.asc failed to download.

curl: (22) The requested URL returned error: 404
Unable to install binary for sdl2
Errors:
URL https://files.retropie.org.uk/binaries/bullseye/vero5/libsdl2-dev_2.0.20+1mali_armhf.deb.asc failed to download.

curl: (22) The requested URL returned error: 404
Unable to install binary for sdl2
FAILED!
```

So it looks like that folder there doesn't exist.

**Comment by hissingshark** [comment]
That's because it's trying to download from RetroPie and not my packages hosted at OSMC.
This didn't happen for me, but had for someone else -  and was one of the things I wanted to try on a re-install with a fresh image.

I had a feeling it was due to `gpg-agent` not being installed by default.  It may have reported that higher up the log.

Can you please check the output of: `apt-cache policy gpg-agent` 
If it isn't installed run `sudo apt-get install gpg-agent`.  You may need a reboot after that, to ensure it's running before you try again.

**Comment by dbischof90** [comment]
Okay, that worked - other issues now but that's for a different issue. Thanks!
